version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      # allow anyone to connect - even without a password
      # only use for running locally or in CI/CD
      POSTGRES_HOST_AUTH_METHOD: trust
      # create a role with name
      POSTGRES_USER: postgres
      # create database test-node-with-docker
      POSTGRES_DB: wallet
    ports:
      - '2345:5432'
  # redis:
  #   image: redis
  #   container_name: redis
  #   ports:
  #     - '6378:6378'
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      DB_HOST: postgres
      DB_NAME: wallet
      DB_PORT: 5432
      DB_USER: postgres
    depends_on:
      - postgres
      # - redis
